# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    trusted_hosts: ['%env(TRUSTED_HOSTS)%']

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    serializer:
        name_converter: 'serializer.name_converter.camel_case_to_snake_case'

    php_errors:
        log: true

    validation: { enable_annotations: true }

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
